-- CREATE VIEWS WITH CAPITAL DEPARTMENT 
CREATE OR REPLACE VIEW TRAJET AS
SELECT * FROM CITY WHERE ID_CITY IN (SELECT CITY_ID_PREF FROM DEPARTEMENT) AND ID_CITY < 96000 ;

-- INSERT INTO TABLE ROUTE
INSERT INTO ROUTE
SELECT ID_ROUTE.NEXTVAL, D.ID_CITY DEPART_CITY, A.ID_CITY ARRIVAL_CITY
  FROM TRAJET D 
  JOIN TRAJET A ON A.ID_CITY <> D.ID_CITY;